### ISSUE TITLE
[workflow bug] CI doesn't fail when the integration test failed

### ISSUE THREAD

**Issue by tshino** [tshino/vscode-vz-like-keymap#9]

**Comment by tshino** [comment]
Fixed.

**BAD**
```
    - name: Run integration tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm run test_with_vscode
```
**GOOD**
```
    - name: Run integration tests
      run: xvfb-run -a npm run test_with_vscode
      if: runner.os == 'Linux'
    - name: Run integration tests
      run: npm run test_with_vscode
      if: runner.os != 'Linux'
```
